{
 "title": "JWT Pizza",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "New Panel",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_requests_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "http_requests_post_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "http_requests_get_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "http_requests_delete_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "active_users{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pizzas_sold_per_minute_per_min{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizza_revenue_dollars_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pizza_creation_latency_avg_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Authentication Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "auth_attempts_successful_per_minute_per_min{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "auth_attempts_failed_per_minute_per_min{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "endpoint_latency_avg_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}